QOL: Allow quick typing by setting focus on query textarea
tprouvot/Salesforce-Inspector-reloaded pull request #153
Opened 2023-09-10 15:42 UTC by asknet

Problem statement:
Whenever I open data export, the query text area isn't focused. It requires another click to set focus and then start typing.

Solution:
This PR allows to set query textarea as focus on load.

Also new to reactjs development. Please review and suggest.

2023-09-11 07:43 UTC, tprouvot commented
Hi @asknet 
Thanks for this PR ! 

Could you add the new feature description in CHANGES.md file ? (following current convention)

Could you condition this focus based on a localStorage variable (by default false) ?
Since the auto focus triggers the api call to query the object definition, I would prefer to let users decide if they want to enable this or not ?

We should have an option page where users will be able to enable / disable features from this page.
Waiting for this the configuration can be made from chrome dev console.

Thanks a lot !

2023-09-11 14:06 UTC, asknet commented
@tprouvot 

Thanks for the feedback.

Sure, I will update the `CHANGES.md` file.
IMO, by default this should be enabled and can be turned off via setting as suggested. Whenever a data export is launched, I'm under the opinion that user wants to type some query. The only exception is they might choose a query from history or saved ones. Even in such cases, making an extra api call for object definition on focus shouldn't pose a concern.

2023-09-11 15:48 UTC, tprouvot commented
@asknet 
Yes most of the time they will use this page to run a query but not necessarily on the last object queried.
I wouldn't mind to set the autofocus by default to true if the API call is not made.

2023-09-17 20:55 UTC, toly11 commented
I came in here to create a pull request for this exact feature myself:)
Great addition, please merge this.

2023-09-27 09:16 UTC, tprouvot requested changes
Hi @asknet,
I changed my mind, we can enable this param by default and it can be used to disable it.
 Could you accept the suggested changes and also update the CHANGES.md file ? 
Thank you !

2023-09-27 09:16 UTC, tprouvot commented on addon/data-export.js
> +    queryInput.focus();
```suggestion
    //Set the cursor focus on query text area
    if (localStorage.getItem("disableQueryInputAutoFocus") !== "true"){
      queryInput.focus();
    }
```

2023-10-02 03:29 UTC, asknet commented
@tprouvot Thank you. I updated it. Kindly, review.

2023-10-20 06:49 UTC, tprouvot commented on CHANGES.md
> +- In Data export, set input focus in SQOL query text area. [PR153](https://github.com/tprouvot/Salesforce-Inspector-reloaded/pull/153)
```suggestion
- In Data export, set input focus in SQOL query text area. [feature 183](https://github.com/tprouvot/Salesforce-Inspector-reloaded/issues/183) (contribution by [Sarath Addanki](https://github.com/asknet))
```

2023-10-20 06:49 UTC, tprouvot commented
#153

2023-10-20 06:49 UTC, merged

2024-12-02 10:27 UTC, tprouvot commented
Option added to Data Export tab option
<img width="809" alt="image" src="https://github.com/user-attachments/assets/6f928f58-e437-47aa-b2d2-378f534e7a08">