Field Creator merge to ReleaseCandidate
tprouvot/Salesforce-Inspector-reloaded pull request #536
Opened 2024-08-26 19:08 UTC by SantiParris8

## Describe your changes
Implemented the field creator functioanlity.

## Issue ticket number and link
#511

2024-08-27 12:44 UTC, tprouvot commented
Hi @SantiParris8 ,

Thanks for the PR ! 
I'll check it by the end of the week since I just released the 1.24

2024-08-28 11:46 UTC, tprouvot commented on addon/field-creator.js
> +          React.createElement("button", {"aria-label": "Add Row/New field to table",className: "btn btn-sm highlighted", id: "add_row", onClick: this.addRow, style: {maxWidth: "18%"}}, "Add Row")
When clicking on the "Add Row" button, the color does not changed back to blue and stay in grey until we click elsewhere

<img width="557" alt="image" src="https://github.com/user-attachments/assets/c1cfbed7-0178-484e-abfa-3e26d1c45e31">

2024-08-28 11:49 UTC, tprouvot commented on addon/field-creator.js
> +
```suggestion
```

2024-08-28 11:50 UTC, tprouvot commented on addon/field-creator.js
> +
```suggestion
```

2024-08-28 11:50 UTC, tprouvot commented on addon/field-creator.js
> +
```suggestion
```

2024-08-28 11:52 UTC, tprouvot commented on addon/field-creator.js
> +      }
Could you avoid to update the style in the js file ?

2024-08-28 11:53 UTC, tprouvot commented on addon/field-creator.js
> +
```suggestion
```

2024-08-28 11:54 UTC, tprouvot commented on addon/field-creator.js
> +
```suggestion
```

2024-08-28 11:54 UTC, tprouvot commented on addon/field-creator.js
> +
```suggestion
```

2024-08-28 11:54 UTC, tprouvot commented on addon/field-creator.js
> +
```suggestion
```

2024-08-28 11:54 UTC, tprouvot commented on addon/field-creator.js
> +
```suggestion
```

2024-08-28 11:55 UTC, tprouvot commented on addon/field-creator.js
> +
```suggestion
```

2024-08-28 11:59 UTC, tprouvot commented on addon/field-creator.js
> +        React.createElement("h4", {className: "modal-title", style: {textAlign: "center", width: "100%", margin: "0"}}, "Set Field Options"),
Instead of having those inputs in a modal, which may appear as not mandatory, could you integrate the content with label, apiName and type ?
If the line is too small to display all, rendering it on two lines could be OK.

For the permission modal I'm ok with it since there is many info to display

2024-08-28 12:03 UTC, tprouvot commented on addon/field-creator.js
> +            name: label.replace(/\s+/g, "_")
Could you remove the underscore from the name auto generation ?

<img width="810" alt="image" src="https://github.com/user-attachments/assets/d46683aa-1a78-47e2-9a81-aa7890b03c70">

2024-08-28 12:14 UTC, tprouvot commented on addon/field-creator.js
> +    renderTable(profiles, "Profiles"),
Could we have a collapse / uncollapse button for the "Profiles" or "Permission Sets" categories ?
<img width="610" alt="image" src="https://github.com/user-attachments/assets/222c2e14-9fb8-460b-9a09-afc0c259b33c">

2024-08-28 12:17 UTC, tprouvot commented on addon/field-creator.js
> +    }),React.createElement("p", {},"Profile permissions are set to the converted permission set."),
```suggestion
    }),React.createElement("p", {},"Please consider granting field access to Permission Sets"),
```
It can be great to add this documentation link to explain why users should migrate the fields permissions to PermSets
https://admin.salesforce.com/blog/2022/admin-best-practices-for-user-management

2024-08-28 12:23 UTC, tprouvot commented on addon/field-creator.js
> +        React.createElement("use", {xlinkHref: "symbols.svg#error", style: {fill: "#ba0517"}})
Instead of displaying the error in an alert box, can this be displayed under the line with a red font ?
<img width="1287" alt="image" src="https://github.com/user-attachments/assets/7420c8e1-6ff5-4f96-9b53-25633826ad3a">

2024-08-28 12:26 UTC, tprouvot commented on addon/field-creator.js
> +        React.createElement("p", null, "Enter comma separated values of Label, ApiName, Type (Set the separator in Data Export options). "),
```suggestion
        React.createElement("p", null, "Enter " + localStorage.getItem("csvSeparator") : "," + " separated values of Label, ApiName, Type),
```

2024-08-28 12:29 UTC, tprouvot commented on addon/field-creator.js
> +            React.createElement("use", {xlinkHref: "symbols.svg#clone", style: {fill: "#005fb2"}})
when the row is cloned but not deployed yet, the previous status of the deployment is also cloned, could you reset it ?
<img width="1221" alt="image" src="https://github.com/user-attachments/assets/644ac113-68a5-4ba0-a5d3-a5fb049a23ca">

2024-08-28 12:30 UTC, tprouvot commented on addon/field-creator.js
> +            React.createElement("label", {htmlFor: "object_select"}, "Select Object"),
Object selection in the list can be pretty long, by any chance could you use an input search with autocomplete box ?

<img width="682" alt="image" src="https://github.com/user-attachments/assets/e586a989-221a-4e18-97b0-5517e265644a">

2024-08-28 12:31 UTC, tprouvot commented on addon/field-creator.js
> +          React.createElement("a", {href: "#", id: "help-btn", title: "Export Help", onClick: null},
I think it would be great to redirect to the documentation page you created !

2024-08-28 12:41 UTC, tprouvot commented on addon/field-creator.js
> +  };
Haven't tested it a lot but this should allow to import also excel format

```suggestion
  importCsv = () => {
    const {importCsvContent} = this.state;

    // Helper function to detect the separator
    const detectSeparator = (content) => {
      const potentialSeparators = [",", ";", "\t", "|"];
      const lines = content.split("\n").filter(line => line.trim() !== ""); // Remove empty lines

      if (lines.length === 0) {
        return ","; // Default to comma if no content
      }

      // Check the first line for the most frequent separator
      const firstLine = lines[0];
      let maxSeparator = ",";
      let maxCount = 0;

      potentialSeparators.forEach(separator => {
        const count = firstLine.split(separator).length;
        if (count > maxCount) {
          maxCount = count;
          maxSeparator = separator;
        }
      });
      return maxSeparator;
    };

    // Detect separator dynamically
    const separator = detectSeparator(importCsvContent);
    const lines = importCsvContent.split("\n");
    const newFields = [];
    let hasError = false;

    const validTypes = [
      "Checkbox", "Currency", "Date", "DateTime", "Email", "Location", "Number",
      "Percent", "Phone", "Picklist", "MultiselectPicklist", "Text", "TextArea",
      "LongTextArea", "Html", "Url"
    ];

    lines.forEach((line, index) => {
      const [label, name, type] = line.split(separator).map(item => item.trim());
      if (label && name && type) {
        if (validTypes.includes(type)) {
          newFields.push({label, name, type});
        } else {
          this.setState({importError: `Invalid type "${type}" on line ${index + 1}`});
          hasError = true;
        }
      }
    });

    if (!hasError) {
      this.setState(prevState => ({
        fields: [...prevState.fields, ...newFields],
        showImportModal: false,
        importCsvContent: "",
        importError: ""
      }));
    }
  };
```

2024-08-28 12:43 UTC, tprouvot commented on addon/field-creator.js
> +            React.createElement("button", {"aria-label": "Deploy Button", className: "btn btn-large highlighted", onClick: this.deploy}, "Deploy Fields"),
I think that Deploy Fields should be disabled until an object has been selected and one field filled up

<img width="459" alt="image" src="https://github.com/user-attachments/assets/f13e68ea-1db5-47c0-85b0-4ca2cff6e232">

2024-08-28 12:45 UTC, tprouvot commented on addon/field-creator.js
> +      alert("Please select an object first");
It would be great to avoid using alert as much as possible, for this one please check suggestion on disabling the Deploy button

2024-08-28 12:51 UTC, tprouvot commented on addon/field-creator.js
> +            React.createElement("label", {htmlFor: "object_select"}, "Select Object"),
It would be great to provide users a shortcut  link to the setup fields of the object (like we have in the popup object tab)

<img width="512" alt="image" src="https://github.com/user-attachments/assets/41ddc563-d459-421a-8ae2-3c7fd41128b3">

2024-08-28 12:54 UTC, tprouvot requested changes
Hi @SantiParris8,

I have made some suggestions / tests in the review.
Feel free to comment if you need more info or a short meeting ! 

Don't be scared by the number, for many of them it's ideas and improvements, this is already a good feature ! 👏

2024-08-28 12:57 UTC, tprouvot requested changes

2024-08-28 12:57 UTC, tprouvot commented on docs/how-to.md
> +# Field Creator
Instead of adding the info of the Field creator page in the how-to.md, could you create a brand new md file for this feature ? 
As discussed during our previous call, my goal is to split the how-to page into separate pages related to the extensions html pages.
Thanks !

2024-08-28 17:02 UTC, SantiParris8 commented on addon/field-creator.js
> +          React.createElement("button", {"aria-label": "Add Row/New field to table",className: "btn btn-sm highlighted", id: "add_row", onClick: this.addRow, style: {maxWidth: "18%"}}, "Add Row")
Fixed by order of css atributes active/focus

2024-08-28 17:08 UTC, SantiParris8 commented on addon/field-creator.js
> +      }
Created CSS class, applied to both modals.

2024-08-28 17:23 UTC, SantiParris8 commented on addon/field-creator.js
> +            name: label.replace(/\s+/g, "_")
Replaced to auto camel case
`label.replace(/\s+(\w)/g, (_, letter) => letter.toUpperCase())`
Test tpr will now be: TestTpr

2024-08-28 20:15 UTC, SantiParris8 commented on addon/field-creator.js
> +    React.createElement("div", {
Fixed, footer is always visible

2024-08-28 20:16 UTC, SantiParris8 commented on addon/field-creator.js
> +    renderTable(profiles, "Profiles"),
Done, permission sets are first and expanded, both are collapsable.

2024-08-28 21:01 UTC, SantiParris8 commented on addon/field-creator.js
> +            React.createElement("use", {xlinkHref: "symbols.svg#clone", style: {fill: "#005fb2"}})
This is now fixed. removing status prior to cloning.

2024-08-28 21:01 UTC, SantiParris8 commented on addon/field-creator.js
> +            React.createElement("label", {htmlFor: "object_select"}, "Select Object"),
Search is now implemented.

2024-08-28 21:03 UTC, SantiParris8 commented on addon/field-creator.js
> +  };
Created an excel file to test and seems to be working, implemented.

2024-08-28 21:09 UTC, SantiParris8 commented on addon/field-creator.js
> +            React.createElement("label", {htmlFor: "object_select"}, "Select Object"),
Implemented, fields dynamically appears and is clickable, shows the fields for the object

2024-08-28 21:09 UTC, SantiParris8 commented on addon/field-creator.js
> +            React.createElement("button", {"aria-label": "Deploy Button", className: "btn btn-large highlighted", onClick: this.deploy}, "Deploy Fields"),
Implemented, disabled until an object is clicked.

2024-08-28 21:10 UTC, SantiParris8 commented on addon/field-creator.js
> +      alert("Please select an object first");
Implemented.

2024-08-28 21:12 UTC, SantiParris8 commented on addon/field-creator.js
> +        React.createElement("p", null, "Enter comma separated values of Label, ApiName, Type (Set the separator in Data Export options). "),
Sintax was a bit diff but implemented.

`        React.createElement("p", null, "Enter " + (localStorage.getItem("csvSeparator") || ",") + "  separated values of Label, ApiName, Type."),
`

2024-08-28 21:13 UTC, SantiParris8 commented on addon/field-creator.js
> +        React.createElement("use", {xlinkHref: "symbols.svg#error", style: {fill: "#ba0517"}})
@tprouvot I really like the option of clicking the icon to view the error, maybe I can implement a pop up if alerts are to be avoided? Awaiting you response on this to implement the solution.

2024-08-28 21:15 UTC, SantiParris8 commented on addon/field-creator.js
> +        React.createElement("h4", {className: "modal-title", style: {textAlign: "center", width: "100%", margin: "0"}}, "Set Field Options"),
@tprouvot I believe the modal is a better approach since some of the field types have a really long list of properties that can be set, for checkboxes,texts,dates the options are optional so I thionk the modal is really the optimal way to present this information. Do you agree? Thank you for your response and inputs.

2024-08-28 21:17 UTC, SantiParris8 commented on docs/how-to.md
> +# Field Creator
Moved to doc/field-creator.md

2024-08-28 21:21 UTC, SantiParris8 commented on addon/field-creator.js
> +          React.createElement("a", {href: "#", id: "help-btn", title: "Export Help", onClick: null},
Implemented! Points to docs/field-creator.md

2024-08-28 21:43 UTC, SantiParris8 commented on addon/field-creator.js
> +    const permissionPromises = field.profiles.map(profile => {
Implemented red text to indicate fields are missiing profiles.

2024-08-29 17:41 UTC, SantiParris8 commented on addon/field-creator.js
> +        React.createElement("use", {xlinkHref: "symbols.svg#error", style: {fill: "#ba0517"}})
Reworked into salesforce toast messages.

![image](https://github.com/user-attachments/assets/c4185a15-a872-4dce-befa-65c9ee8d6f3f)

2024-08-30 09:17 UTC, tprouvot commented
Great thank you for those updates, let me check it

2024-08-30 09:22 UTC, tprouvot commented on addon/field-creator.js
> +              }, "(Fields)"), React.createElement("br", null),
Could you check the css to keep the href color button always blue ?
<img width="462" alt="image" src="https://github.com/user-attachments/assets/d47b8c35-571f-474d-a4f4-4e800f41e62e">

Please check the code on the popup to have the link working also for CMDT

2024-08-30 09:24 UTC, tprouvot commented on addon/field-creator.js
> +              React.createElement("label", {htmlFor: "object_select"}, "Select Object"),
Could you sort the results by displaying the managed object after the standard ones ? 

<img width="478" alt="image" src="https://github.com/user-attachments/assets/ee5f9d1f-d386-4073-8ea5-82dfdb0d6507">

2024-08-30 09:35 UTC, tprouvot commented on addon/field-creator.js
> +      }), React.createElement("p", {}, "Please consider granting field access to Permission Sets."),
```suggestion
React.createElement("p", {}, "Please consider granting field access to Permission Sets instead of Profiles ",
        React.createElement("a", {href: "https://admin.salesforce.com/blog/2023/permissions-updates-learn-moar-spring-23", target: ""}, "?")
      ),
```

2024-08-30 09:42 UTC, tprouvot commented on addon/field-creator.js
> +              !this.state.allFieldsHavePermissions && React.createElement("p", {style: {color: "red"}}, "Some fields are missing permissions"),
You should not block the deployment if the field has no permissions (specially for CMDT where it is not required)
I think you did as a kind of reminder, you can display a kind of warning under the field row instead of this message if a field has no permission associated

2024-08-30 09:43 UTC, tprouvot commented on addon/field-creator.js
> +      this.setState({fieldErrorMessage: "Field has not been deployed yet"});
You may have a bug here since the deployment is ok but when clicking on the icon the error toast is displayed

<img width="1123" alt="image" src="https://github.com/user-attachments/assets/2dba0033-7c52-4939-a294-15a9bb090e21">

2024-08-30 09:45 UTC, tprouvot commented on addon/field-creator.js
> +            React.createElement("th", {style: {width: "20%"}}, "API Name (__c)"), // make the lables/th clearly part of the table.
If the API Name is updated after a successful deployment, the icon status persist. I think this should erase the status

<img width="1192" alt="image" src="https://github.com/user-attachments/assets/17f78927-4ca3-4d8a-95a0-d778d3fbfddc">

2024-08-30 09:50 UTC, tprouvot commented on addon/field-creator.js
> +        React.createElement("thead", null,
Instead of repeating the `React.createElement,` could you use the same structure as in the other pages ? `let h = React.createElement;`

2024-08-30 09:50 UTC, tprouvot requested changes
Thanks for all the updates you've made, here's some few more 😄

2024-08-30 09:53 UTC, tprouvot commented on addon/field-creator.js
> +          React.createElement("a", {href: "https://github.com/SantiParris8/Salesforce-Inspector-reloaded-fieldCreator/blob/releaseCandidate/docs/field-creator.md", target: "_blank", id: "help-btn", t
```suggestion
          React.createElement("a", {href: "https://tprouvot.github.io/Salesforce-Inspector-reloaded/field-creator/", target: "_blank", id: "help-btn", title: "Field Creator Help", onClick: null},
```

2024-08-30 09:54 UTC, tprouvot requested changes
Update link to doc website

2024-08-30 16:12 UTC, SantiParris8 commented on addon/field-creator.js
> +      }), React.createElement("p", {}, "Please consider granting field access to Permission Sets."),
Implemented

2024-08-30 16:18 UTC, SantiParris8 commented on addon/field-creator.js
> +        React.createElement("thead", null,
Done

2024-08-30 16:19 UTC, SantiParris8 commented on addon/field-creator.js
> +          React.createElement("a", {href: "https://github.com/SantiParris8/Salesforce-Inspector-reloaded-fieldCreator/blob/releaseCandidate/docs/field-creator.md", target: "_blank", id: "help-btn", t
Implemented

2024-08-30 16:28 UTC, SantiParris8 commented on addon/field-creator.js
> +              }, "(Fields)"), React.createElement("br", null),
Color blue is implemented. Pending the CMDT dynamic link.

2024-09-01 16:13 UTC, SantiParris8 commented on addon/field-creator.js
> +              !this.state.allFieldsHavePermissions && React.createElement("p", {style: {color: "red"}}, "Some fields are missing permissions"),
Changed this, also implemented a quick fix since the issue of Cannot read properties of undefined (reading 'map') was back but fixed it. Now it allows to deploy fields without profiles.

2024-09-01 16:19 UTC, SantiParris8 commented on addon/field-creator.js
> +            React.createElement("th", {style: {width: "20%"}}, "API Name (__c)"), // make the lables/th clearly part of the table.
Fixed, status is erased if api Name changes.

2024-09-06 18:18 UTC, SantiParris8 commented on addon/field-creator.js
> +              }, "(Fields)"), React.createElement("br", null),
CMDT Dynamic link implemented

2024-09-07 12:58 UTC, SantiParris8 commented on addon/field-creator.js
> +              React.createElement("label", {htmlFor: "object_select"}, "Select Object"),
Reworked the way the search algorithm prioritizes searches. It is not done based on the managed and standard but It works more intuitively.

2024-09-09 13:51 UTC, tprouvot requested changes

2024-09-09 19:48 UTC, SantiParris8 commented on addon/field-creator.js
> +          flexDirection: "column"
Fixed modal-dialog css.

2024-09-09 20:33 UTC, SantiParris8 commented on addon/field-creator.js
> +              h("th", {style: {padding: "8px", textAlign: "left", borderBottom: "1px solid #ddd"}}, "Name"),
Moved to css classes.

2024-09-17 19:45 UTC, tprouvot approved these changes
Thanks for the updates @SantiParris8 ! 👍

2024-09-17 19:46 UTC, merged